easydigitaldownloads/edd-custom-functions

- custom-functions.php
- includes/taxonomies.php
Includes a new file for taxonomy related functions and registers three taxonomies. Working towards https://github.com/easydigitaldownloads/EDD-Site/issues/950
> Register gateway taxonomies

- includes/taxonomies.php
> change gateway taxonomy slugs #13

- custom-functions.php
> Add upgrade path to all access pass

- includes/extensions/recurring-payments-functions.php
#42 Let's save the code for now.
> remove subscription cancellation confirmation #42

- includes/extensions/all-access-functions.php
For EDD site issue: https://github.com/easydigitaldownloads/EDD-Site/issues/1341
> base AAP upgrade discount on actual AAP price

- includes/edd-filters-actions.php
> Allow sessions on the discounts archive list #48

- includes/extensions/software-licensing-functions.php
I've fixed this on Staging now:
> Fix activate/deactivate/check_license calls for MailChimp

- includes/post-types/metaboxes.php
See #58 
* Adds a one-size-fits-all metabox to Posts and a single text field with a meta_key of `_subtitles` so that its value saves in the same fashion as the Subtitles plugin, which isn't currently compatible with WordPress 5.0+.
> Update for EDD Site 3.0.1

- includes/edd-filters-actions.php
> Conditinally load StripeJS, don't start session on blog posts #60

- includes/edd-filters-actions.php
1) Removes all changelogs from the options
2) Unhooks RCP + EDD Integration
> Performance improvements

- includes/extensions/software-licensing-functions.php
> Move custom license activations for legacy licenses into custom function #70

- includes/3rd-party-plugin-functions.php
> Change filter used for disabling auto renew #82

- includes/3rd-party-plugin-functions.php
- includes/post-types/metaboxes.php
See #84
For the best description of what's happening here, please see the EDD site PR that goes along with this PR: https://github.com/easydigitaldownloads/EDD-Site/pull/1503
> adjust Simple Notices Pro support for multiple use cases

- includes/extensions/all-access-functions.php
See #86 
See #87 
The overall purpose of both issues is to add support for the Lifetime All Access Pass. There's a bit of refactoring going on as well. This works alongside theme updates, so some things are slightly out of context.
> Add support for Lifetime All Access Pass

- includes/extensions/all-access-functions.php
> add missing user ID parameter

- includes/extensions/all-access-functions.php
> Unset billing_cycle_anchor when upgrading

- includes/extensions/all-access-functions.php
> Dev->Master: Unset billing_cycle_anchor when upgrading

- includes/extensions/software-licensing-functions.php
> make sure MailPoet users get updates after download name change - issue/94

- includes/3rd-party-plugin-functions.php
> Add custom notification for Gravity Forms to notify when HS disconnects #96

- .github/workflows/pagely-deploy-live.yml
- .github/workflows/pagely-deploy-staging.yml
- includes/extensions/software-licensing-functions.php
See #105
@SDavisMedia This is against `master` branch - not sure if that's right. Feel free to adjust accordingly.
EDIT by Sean: I changed "Closes" to "See" in reference to the issue because I changed the PR to be against `dev` instead of `master`. So we don't want the issue to close just yet as I merge this into `dev`.
> Add support for getting order date in EDD 3.0 #105

- includes/extensions/all-access-functions.php
- includes/extensions/software-licensing-functions.php
Closes #104
Tested on staging and all is well. No unexpected issues.
> Issue/104 - Check for 'complete' status in addition to 'publish' 

- includes/extensions/all-access-functions.php
Closes #103
Tested on staging and all is well.
> Issue/103 - Exit early if there's no payment ID or customer ID 

- custom-functions.php
- includes/settings/main.php
> issue/113 - introduce Site Settings admin page 
